//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentes
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public commande()
        {
            this.detailsCommandes = new HashSet<detailsCommandes>();
        }
    
        public int numCommande { get; set; }
        public System.DateTime dateCommande { get; set; }
        public string Etat { get; set; }
        public int numClient { get; set; }
        public int numFacture { get; set; }
        public int numPaiement { get; set; }
        public string Total_HT { get; set; }
        public string TVA { get; set; }
        public string Total_TTC { get; set; }
    
        public virtual client client { get; set; }
        public virtual facture facture { get; set; }
        public virtual paiement paiement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailsCommandes> detailsCommandes { get; set; }
    }
}
