//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbVentes : DbContext
    {
        public dbVentes()
            : base("name=dbVentes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<departement> departement { get; set; }
        public virtual DbSet<detailsCommandes> detailsCommandes { get; set; }
        public virtual DbSet<facture> facture { get; set; }
        public virtual DbSet<paiement> paiement { get; set; }
        public virtual DbSet<produit> produit { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
