//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbVenteContext : DbContext
    {
        public dbVenteContext()
            : base("name=dbVenteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorie> categories { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<commande> commandes { get; set; }
        public virtual DbSet<departement> departements { get; set; }
        public virtual DbSet<detailsCommandes> detailsCommandes { get; set; }
        public virtual DbSet<facture> factures { get; set; }
        public virtual DbSet<paiement> paiements { get; set; }
        public virtual DbSet<produit> produits { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
